# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Juan Antonio Montero de Espinosa Reina
tagline:          'Blog on Econometrics with a focus on Spain'
description:      'A blog to share my findings about Econometrics, Data Analysis and anything related'
url:              https://fongandrew.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Juan Antonio Montero de Espinosa Reina'
  url:            add_my_twitter

paginate:         3
paginate_path:    'blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  false
sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
